// List of all portfolio images from assets/ALUBM VILLA/
const List<String> portfolioImages = [
  'assets/ALUBM VILLA/1  (1).jpg',
  'assets/ALUBM VILLA/1  (2).jpg',
  'assets/ALUBM VILLA/1 (2).jpg',
  'assets/ALUBM VILLA/1 (3).jpg',
  'assets/ALUBM VILLA/1 (4).jpg',
  'assets/ALUBM VILLA/1 (5).jpg',
  'assets/ALUBM VILLA/1 (6).jpg',
  'assets/ALUBM VILLA/2 (1).jpg',
  'assets/ALUBM VILLA/2 (2).jpg',
  'assets/ALUBM VILLA/2 (3).jpg',
  'assets/ALUBM VILLA/2 (4).jpg',
  'assets/ALUBM VILLA/2 (5).jpg',
  'assets/ALUBM VILLA/2 (7).jpg',
  'assets/ALUBM VILLA/2.jpg',
  'assets/ALUBM VILLA/3 (1).jpg',
  'assets/ALUBM VILLA/3 (2).jpg',
  'assets/ALUBM VILLA/3 (3).jpg',
  'assets/ALUBM VILLA/3 (4).jpg',
  'assets/ALUBM VILLA/4 (1).jpg',
  'assets/ALUBM VILLA/4 (2).jpg',
  'assets/ALUBM VILLA/4 (3).jpg',
  'assets/ALUBM VILLA/4 (4).jpg',
  'assets/ALUBM VILLA/4 (5).jpg',
  'assets/ALUBM VILLA/4 (6).jpg',
  'assets/ALUBM VILLA/4 (8).jpg',
  'assets/ALUBM VILLA/4 (9).jpg',
  'assets/ALUBM VILLA/5 ( 7.jpg',
  'assets/ALUBM VILLA/5 (1).jpg',
  'assets/ALUBM VILLA/5 (2).jpg',
  'assets/ALUBM VILLA/5 (3).jpg',
  'assets/ALUBM VILLA/5 (4).jpg',
  'assets/ALUBM VILLA/5 (5).jpg',
  'assets/ALUBM VILLA/5 (6).jpg',
  'assets/ALUBM VILLA/5 (7).jpg',
  'assets/ALUBM VILLA/6 (2).jpg',
  'assets/ALUBM VILLA/6 (3).jpg',
  'assets/ALUBM VILLA/6 (5).jpg',
  'assets/ALUBM VILLA/6 (7).jpg',
  'assets/ALUBM VILLA/7 (1).jpg',
  'assets/ALUBM VILLA/7 (2).jpg',
  'assets/ALUBM VILLA/7 (3).jpg',
  'assets/ALUBM VILLA/7 (4).jpg',
  'assets/ALUBM VILLA/8 (1).jpg',
  'assets/ALUBM VILLA/8 (2).jpg',
  'assets/ALUBM VILLA/8 (3).jpg',
  'assets/ALUBM VILLA/8 (4).jpg',
  'assets/ALUBM VILLA/9 (1).jpg',
  'assets/ALUBM VILLA/9 (2).jpg',
  'assets/ALUBM VILLA/9 (3).jpg',
  'assets/ALUBM VILLA/9 (4).jpg',
  'assets/ALUBM VILLA/9 (5).jpg',
];

// Hero slides (first 5 for the hero slideshow)
List<String> get heroImages => portfolioImages.take(5).toList();
